project:
  type: manuscript
  output-dir: ../../docs/projects/TalmiEEG
  render:
    - index.qmd

manuscript:
  code-links: repo

execute:
  freeze: auto

format:
  html:
    default: true
    toc: true
    theme: darkly
  apaquarto-pdf:
    nocorrespondence: true
    donotrepeattitle: true
    draftfirst: true
    filters:
      - abstract-section
  apaquarto-docx:
    nocorrespondence: true
    donotrepeattitle: true

format-links: [apaquarto-docx, apaquarto-pdf]
