project:
  render:
    - Manuscript_260219.md

format:
  apaquarto-pdf:
    nocorrespondence: true
    donotrepeattitle: true
    draftfirst: true
    header-includes:
      - \usepackage{soul}
    filters:
      - abstract-section
