<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Robin Hellerstedt">
<meta name="author" content="Jordan Gunn">
<meta name="author" content="Deborah Talmi">

<title>Contribution of the Late Positive Potential to Emotional Memory: A Joint Neuro-Cognitive Approach to Memory Prediction</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-4d9afe2b8d18ee9fa5d0d57b5ed4214d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-fcc3bc6eb91de46a6ea40c6d96a0da9b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="dark">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta name="citation_title" content="Contribution of the Late Positive Potential to Emotional Memory: A Joint Neuro-Cognitive Approach to Memory Prediction">
<meta name="citation_author" content="Robin Hellerstedt">
<meta name="citation_author" content="Jordan Gunn">
<meta name="citation_author" content="Deborah Talmi">
<meta name="citation_language" content="en">
<meta name="citation_reference" content="citation_title=Model selection and multimodel inference: A practical information-theoretic approach;,citation_author=Kenneth P. Burnham;,citation_author=David R. Anderson;,citation_publication_date=2002;,citation_cover_date=2002;,citation_year=2002;,citation_doi=10.1007/b97636;">
<meta name="citation_reference" content="citation_title=Data analysis using regression and multilevel/hierarchical models;,citation_author=Andrew Gelman;,citation_author=Jennifer Hill;,citation_publication_date=2006;,citation_cover_date=2006;,citation_year=2006;,citation_doi=10.1017/CBO9780511790942;">
<meta name="citation_reference" content="citation_title=Affective influences on the attentional dynamics supporting awareness;,citation_author=Adam K. Anderson;,citation_publication_date=2005;,citation_cover_date=2005;,citation_year=2005;,citation_issue=2;,citation_doi=10.1037/0096-3445.134.2.258;,citation_volume=134;,citation_journal_title=Journal of Experimental Psychology: General;">
<meta name="citation_reference" content="citation_title=Local context influences memory for emotional stimuli but not electrophysiological markers of emotion-dependent attention;,citation_author=Grace E. Barnacle;,citation_author=Dimitris Tsivilis;,citation_author=Alexandre Schaefer;,citation_author=Deborah Talmi;,citation_publication_date=2018;,citation_cover_date=2018;,citation_year=2018;,citation_issue=4;,citation_doi=10.1111/psyp.13014;,citation_volume=55;,citation_journal_title=Psychophysiology;">
<meta name="citation_reference" content="citation_title=Fitting linear mixed-effects models using lme4;,citation_author=Douglas Bates;,citation_author=Martin Mächler;,citation_author=Ben Bolker;,citation_author=Steve Walker;,citation_publication_date=2015;,citation_cover_date=2015;,citation_year=2015;,citation_issue=1;,citation_doi=10.18637/jss.v067.i01;,citation_volume=67;,citation_journal_title=Journal of Statistical Software;">
<meta name="citation_reference" content="citation_title=The geneva affective picture database (GAPED): A new 730-picture database focusing on valence and normative significance;,citation_author=Elise S. Dan-Glauser;,citation_author=Klaus R. Scherer;,citation_publication_date=2011;,citation_cover_date=2011;,citation_year=2011;,citation_issue=2;,citation_doi=10.3758/s13428-011-0064-1;,citation_volume=43;,citation_journal_title=Behavior Research Methods;">
<meta name="citation_reference" content="citation_title=EEGLAB: An open source toolbox for analysis of single-trial EEG dynamics including independent component analysis;,citation_author=Arnaud Delorme;,citation_author=Scott Makeig;,citation_publication_date=2004;,citation_cover_date=2004;,citation_year=2004;,citation_issue=1;,citation_doi=10.1016/j.jneumeth.2003.10.009;,citation_volume=134;,citation_journal_title=Journal of Neuroscience Methods;">
<meta name="citation_reference" content="citation_title=An R companion to applied regression;,citation_author=John Fox;,citation_author=Sanford Weisberg;,citation_publication_date=2019;,citation_cover_date=2019;,citation_year=2019;">
<meta name="citation_reference" content="citation_title=Contiguity in episodic memory;,citation_author=M. Karl Healey;,citation_author=Nicole M. Long;,citation_author=Michael J. Kahana;,citation_publication_date=2019;,citation_cover_date=2019;,citation_year=2019;,citation_issue=3;,citation_doi=10.3758/s13423-018-1537-3;,citation_volume=26;,citation_journal_title=Psychonomic Bulletin &amp;amp;amp; Review;">
<meta name="citation_reference" content="citation_title=A distributed representation of temporal context;,citation_author=Marc W. Howard;,citation_author=Michael J. Kahana;,citation_publication_date=2002;,citation_cover_date=2002;,citation_year=2002;,citation_issue=3;,citation_doi=10.1006/jmps.2001.1388;,citation_volume=46;,citation_journal_title=Journal of Mathematical Psychology;">
<meta name="citation_reference" content="citation_title=International affective picture system (IAPS): Affective ratings of pictures and instruction manual;,citation_author=Peter J. Lang;,citation_author=Margaret M. Bradley;,citation_author=Bruce N. Cuthbert;,citation_publication_date=2005;,citation_cover_date=2005;,citation_year=2005;,citation_technical_report_institution=University of Florida;">
<meta name="citation_reference" content="citation_title=Emmeans: Estimated marginal means, aka least-squares means;,citation_author=Russell V. Lenth;,citation_publication_date=2024;,citation_cover_date=2024;,citation_year=2024;,citation_fulltext_html_url=https://CRAN.R-project.org/package=emmeans;">
<meta name="citation_reference" content="citation_title=Relations between emotion, memory, and attention: Evidence from taboo Stroop, lexical decision, and immediate memory tasks;,citation_author=Donald G. MacKay;,citation_author=Meredith Shafto;,citation_author=Jennifer K. Taylor;,citation_author=Diane E. Marian;,citation_author=Lise Abrams;,citation_author=Jennifer R. Dyer;,citation_publication_date=2004;,citation_cover_date=2004;,citation_year=2004;,citation_issue=3;,citation_doi=10.3758/BF03195840;,citation_volume=32;,citation_journal_title=Memory &amp;amp;amp; Cognition;">
<meta name="citation_reference" content="citation_title=Investigating the functional utility of the left parietal ERP old/new effect: Brain activity predicts within but not between participant variance in episodic recollection;,citation_author=Catherine A. MacLeod;,citation_author=David I. Donaldson;,citation_publication_date=2017;,citation_cover_date=2017;,citation_year=2017;,citation_doi=10.3389/fnhum.2017.00580;,citation_volume=11;,citation_journal_title=Frontiers in Human Neuroscience;">
<meta name="citation_reference" content="citation_title=Nonparametric statistical testing of EEG- and MEG-data;,citation_author=Eric Maris;,citation_author=Robert Oostenveld;,citation_publication_date=2007;,citation_cover_date=2007;,citation_year=2007;,citation_issue=1;,citation_doi=10.1016/j.jneumeth.2007.03.024;,citation_volume=164;,citation_journal_title=Journal of Neuroscience Methods;">
<meta name="citation_reference" content="citation_title=FASTER: Fully automated statistical thresholding for EEG artifact rejection;,citation_author=Hugh Nolan;,citation_author=Robert Whelan;,citation_author=Richard B. Reilly;,citation_publication_date=2010;,citation_cover_date=2010;,citation_year=2010;,citation_issue=1;,citation_doi=10.1016/j.jneumeth.2010.07.015;,citation_volume=192;,citation_journal_title=Journal of Neuroscience Methods;">
<meta name="citation_reference" content="citation_title=FieldTrip: Open source software for advanced analysis of MEG, EEG, and invasive electrophysiological data;,citation_author=Robert Oostenveld;,citation_author=Pascal Fries;,citation_author=Eric Maris;,citation_author=Jan-Mathijs Schoffelen;,citation_publication_date=2011;,citation_cover_date=2011;,citation_year=2011;,citation_doi=10.1155/2011/156869;,citation_volume=2011;,citation_journal_title=Computational Intelligence and Neuroscience;">
<meta name="citation_reference" content="citation_title=A context maintenance and retrieval model of organizational processes in free recall;,citation_author=Sean M. Polyn;,citation_author=Kenneth A. Norman;,citation_author=Michael J. Kahana;,citation_publication_date=2009;,citation_cover_date=2009;,citation_year=2009;,citation_issue=1;,citation_doi=10.1037/a0014420;,citation_volume=116;,citation_journal_title=Psychological Review;">
<meta name="citation_reference" content="citation_title=Category-specific cortical activity precedes retrieval during memory search;,citation_author=Sean M. Polyn;,citation_author=Vaidehi S. Natu;,citation_author=Jonathan D. Cohen;,citation_author=Kenneth A. Norman;,citation_publication_date=2005;,citation_cover_date=2005;,citation_year=2005;,citation_issue=5756;,citation_doi=10.1126/science.1117645;,citation_volume=310;,citation_journal_title=Science;">
<meta name="citation_reference" content="citation_title=Brain mechanisms for emotional influences on perception and attention: What is magic and what is not;,citation_author=Gilles Pourtois;,citation_author=Antonio Schettino;,citation_author=Patrik Vuilleumier;,citation_publication_date=2013;,citation_cover_date=2013;,citation_year=2013;,citation_issue=3;,citation_doi=10.1016/j.biopsycho.2012.02.007;,citation_volume=92;,citation_journal_title=Biological Psychology;">
<meta name="citation_reference" content="citation_title=The neural representations of emotional experiences are more similar than those of neutral experiences;,citation_author=Matteo Riberto;,citation_author=Rony Paz;,citation_author=Gorana Pobric;,citation_author=Deborah Talmi;,citation_publication_date=2022;,citation_cover_date=2022;,citation_year=2022;,citation_issue=13;,citation_doi=10.1523/JNEUROSCI.1490-21.2022;,citation_volume=42;,citation_journal_title=The Journal of Neuroscience;">
<meta name="citation_reference" content="citation_title=P300 in detecting concealed information and deception: A review;,citation_author=J. Peter Rosenfeld;,citation_publication_date=2020;,citation_cover_date=2020;,citation_year=2020;,citation_issue=7;,citation_doi=10.1111/psyp.13362;,citation_volume=57;,citation_journal_title=Psychophysiology;">
<meta name="citation_reference" content="citation_title=A systems approach to appraisal mechanisms in emotion;,citation_author=David Sander;,citation_author=Didier Grandjean;,citation_author=Klaus R. Scherer;,citation_publication_date=2005;,citation_cover_date=2005;,citation_year=2005;,citation_issue=4;,citation_doi=10.1016/j.neunet.2005.03.001;,citation_volume=18;,citation_journal_title=Neural Networks;">
<meta name="citation_reference" content="citation_title=Cluster-based permutation tests of MEG/EEG data do not establish significance of effect latency or location;,citation_author=Jona Sassenhagen;,citation_author=Dejan Draschkow;,citation_publication_date=2019;,citation_cover_date=2019;,citation_year=2019;,citation_issue=6;,citation_doi=10.1111/psyp.13335;,citation_volume=56;,citation_journal_title=Psychophysiology;">
<meta name="citation_reference" content="citation_title=Emotion and attention: Event-related brain potential studies;,citation_author=Harald T. Schupp;,citation_author=Tobias Flaisch;,citation_author=Jessica Stockburger;,citation_author=Markus Junghöfer;,citation_publication_date=2006;,citation_cover_date=2006;,citation_year=2006;,citation_doi=10.1016/S0079-6123(06)56002-9;,citation_volume=156;,citation_inbook_title=Progress in brain research;">
<meta name="citation_reference" content="citation_title=Case-by-case: Emotional stimulus significance and the modulation of the EPN and LPP;,citation_author=Harald T. Schupp;,citation_author=Uwe M. Kirmse;,citation_publication_date=2021;,citation_cover_date=2021;,citation_year=2021;,citation_issue=4;,citation_doi=10.1111/psyp.13766;,citation_volume=58;,citation_journal_title=Psychophysiology;">
<meta name="citation_reference" content="citation_title=Autonomic specificity of basic emotions: Evidence from pattern classification and cluster analysis;,citation_author=Christine L. Stephens;,citation_author=Ian C. Christie;,citation_author=Bruce H. Friedman;,citation_publication_date=2010;,citation_cover_date=2010;,citation_year=2010;,citation_issue=3;,citation_doi=10.1016/j.biopsycho.2010.03.014;,citation_volume=84;,citation_journal_title=Biological Psychology;">
<meta name="citation_reference" content="citation_title=Differential evolution – a simple and efficient heuristic for global optimization over continuous spaces;,citation_author=Rainer Storn;,citation_author=Kenneth Price;,citation_publication_date=1997;,citation_cover_date=1997;,citation_year=1997;,citation_issue=4;,citation_doi=10.1023/A:1008202821328;,citation_volume=11;,citation_journal_title=Journal of Global Optimization;">
<meta name="citation_reference" content="citation_title=A retrieved context model of the emotional modulation of memory;,citation_author=Deborah Talmi;,citation_author=Lynn J. Lohnas;,citation_author=Nathaniel D. Daw;,citation_publication_date=2019;,citation_cover_date=2019;,citation_year=2019;,citation_issue=4;,citation_doi=10.1037/rev0000132;,citation_volume=126;,citation_journal_title=Psychological Review;">
<meta name="citation_reference" content="citation_title=The contribution of relatedness and distinctiveness to emotionally-enhanced memory;,citation_author=Deborah Talmi;,citation_author=Brian T. C. Luk;,citation_author=Lucy M. McGarry;,citation_author=Morris Moscovitch;,citation_publication_date=2007;,citation_cover_date=2007;,citation_year=2007;,citation_issue=4;,citation_doi=10.1016/j.jml.2007.01.002;,citation_volume=56;,citation_journal_title=Journal of Memory and Language;">
<meta name="citation_reference" content="citation_title=Accounting for immediate emotional memory enhancement;,citation_author=Deborah Talmi;,citation_author=Lucy M. McGarry;,citation_publication_date=2012;,citation_cover_date=2012;,citation_year=2012;,citation_issue=1;,citation_doi=10.1016/j.jml.2011.07.009;,citation_volume=66;,citation_journal_title=Journal of Memory and Language;">
<meta name="citation_reference" content="citation_title=Why more is better: Simultaneous modeling of EEG, fMRI, and behavioral data;,citation_author=Brandon M. Turner;,citation_author=Claudia A. Rodriguez;,citation_author=Tony M. Norcia;,citation_author=Samuel M. McClure;,citation_author=Mark Steyvers;,citation_publication_date=2016;,citation_cover_date=2016;,citation_year=2016;,citation_doi=10.1016/j.neuroimage.2015.12.030;,citation_volume=128;,citation_journal_title=NeuroImage;">
<meta name="citation_reference" content="citation_title=EmoPics: Subjektive und psychophysiologische evaluationen neuen bildmaterials für die klinisch-bio-psychologische forschung;,citation_author=Michèle Wessa;,citation_author=Philipp Kanske;,citation_author=Paul Neumeister;,citation_author=Klaus Bode;,citation_author=Johanna Heissler;,citation_author=Susanne Schönfelder;,citation_publication_date=2010;,citation_cover_date=2010;,citation_year=2010;,citation_issue=1/11;,citation_volume=Supplement;,citation_journal_title=Zeitschrift für Klinische Psychologie und Psychotherapie;">
<meta name="citation_reference" content="citation_title=Interactions between attention and memory;,citation_author=Marvin M. Chun;,citation_author=Nicholas B. Turk-Browne;,citation_publication_date=2007;,citation_cover_date=2007;,citation_year=2007;,citation_issue=2;,citation_doi=10.1016/j.conb.2007.03.005;,citation_volume=17;,citation_journal_title=Current Opinion in Neurobiology;">
<meta name="citation_reference" content="citation_title=Brain potentials in affective picture processing: Covariation with autonomic arousal and affective report;,citation_author=Bruce N. Cuthbert;,citation_author=Harald T. Schupp;,citation_author=Margaret M. Bradley;,citation_author=Niels Birbaumer;,citation_author=Peter J. Lang;,citation_publication_date=2000;,citation_cover_date=2000;,citation_year=2000;,citation_issue=2;,citation_doi=10.1016/S0301-0511(99)00044-7;,citation_volume=52;,citation_journal_title=Biological Psychology;">
<meta name="citation_reference" content="citation_title=Event-related potentials of emotional memory: Encoding pleasant, unpleasant, and neutral pictures;,citation_author=Florin Dolcos;,citation_author=Roberto Cabeza;,citation_publication_date=2002;,citation_cover_date=2002;,citation_year=2002;,citation_issue=3;,citation_doi=10.3758/CABN.2.3.252;,citation_volume=2;,citation_journal_title=Cognitive, Affective, &amp;amp;amp; Behavioral Neuroscience;">
<meta name="citation_reference" content="citation_title=The P300, the LPP, context updating, and memory: What is the functional significance of the emotion-related late positive potential?;,citation_author=Eric C. Fields;,citation_publication_date=2023;,citation_cover_date=2023;,citation_year=2023;,citation_doi=10.1016/j.ijpsycho.2023.08.005;,citation_volume=192;,citation_journal_title=International Journal of Psychophysiology;">
<meta name="citation_reference" content="citation_title=Human episodic memory retrieval is accompanied by a neural contiguity effect;,citation_author=Sarah Folkerts;,citation_author=Ueli Rutishauser;,citation_author=Marc W. Howard;,citation_publication_date=2018;,citation_cover_date=2018;,citation_year=2018;,citation_issue=17;,citation_doi=10.1523/JNEUROSCI.2312-17.2018;,citation_volume=38;,citation_journal_title=The Journal of Neuroscience;">
<meta name="citation_reference" content="citation_title=Event-related potentials, emotion, and emotion regulation: An integrative review;,citation_author=Greg Hajcak;,citation_author=Annmarie MacNamara;,citation_author=Doreen M. Olvet;,citation_publication_date=2010;,citation_cover_date=2010;,citation_year=2010;,citation_issue=2;,citation_doi=10.1080/87565640903526504;,citation_volume=35;,citation_journal_title=Developmental Neuropsychology;">
<meta name="citation_reference" content="citation_title=Significance?... Significance! Empirical, methodological, and theoretical connections between the late positive potential and P300 as neural responses to stimulus significance: An integrative review;,citation_author=Greg Hajcak;,citation_author=Dan Foti;,citation_publication_date=2020;,citation_cover_date=2020;,citation_year=2020;,citation_issue=7;,citation_doi=10.1111/psyp.13570;,citation_volume=57;,citation_journal_title=Psychophysiology;">
<meta name="citation_reference" content="citation_title=A four-component model of age-related memory change;,citation_author=M. Karl Healey;,citation_author=Michael J. Kahana;,citation_publication_date=2016;,citation_cover_date=2016;,citation_year=2016;,citation_issue=1;,citation_doi=10.1037/rev0000015;,citation_volume=123;,citation_journal_title=Psychological Review;">
<meta name="citation_reference" content="citation_title=Distinct cortical systems reinstate the content and context of episodic memories;,citation_author=James E. Kragel;,citation_author=Youssef Ezzyat;,citation_author=Bradley C. Lega;,citation_author=Michael R. Sperling;,citation_author=Gregory A. Worrell;,citation_author=Robert E. Gross;,citation_author=Barbara C. Jobst;,citation_author=Sameer A. Sheth;,citation_author=Kareem A. Zaghloul;,citation_author=Joel M. Stein;,citation_author=Michael J. Kahana;,citation_publication_date=2021;,citation_cover_date=2021;,citation_year=2021;,citation_doi=10.1038/s41467-021-24393-1;,citation_volume=12;,citation_journal_title=Nature Communications;">
<meta name="citation_reference" content="citation_title=Expanding the scope of memory search: Modeling intralist and interlist effects in free recall;,citation_author=Lynn J. Lohnas;,citation_author=Sean M. Polyn;,citation_author=Michael J. Kahana;,citation_publication_date=2015;,citation_cover_date=2015;,citation_year=2015;,citation_issue=2;,citation_doi=10.1037/a0039036;,citation_volume=122;,citation_journal_title=Psychological Review;">
<meta name="citation_reference" content="citation_title=The role of context in episodic memory: Behavior and neurophysiology;,citation_author=Lynn J. Lohnas;,citation_author=M. Karl Healey;,citation_publication_date=2021;,citation_cover_date=2021;,citation_year=2021;,citation_doi=10.1016/bs.plm.2021.06.003;,citation_volume=75;,citation_inbook_title=Psychology of learning and motivation;">
<meta name="citation_reference" content="citation_title=Oscillatory patterns in temporal lobe reveal context reinstatement during memory search;,citation_author=Jeremy R. Manning;,citation_author=Sean M. Polyn;,citation_author=Gordon H. Baltuch;,citation_author=Brian Litt;,citation_author=Michael J. Kahana;,citation_publication_date=2011;,citation_cover_date=2011;,citation_year=2011;,citation_issue=31;,citation_doi=10.1073/pnas.1015174108;,citation_volume=108;,citation_journal_title=Proceedings of the National Academy of Sciences;">
<meta name="citation_reference" content="citation_title=Arousal-biased competition in perception and memory;,citation_author=Mara Mather;,citation_author=Matthew R. Sutherland;,citation_publication_date=2011;,citation_cover_date=2011;,citation_year=2011;,citation_issue=2;,citation_doi=10.1177/1745691611400234;,citation_volume=6;,citation_journal_title=Perspectives on Psychological Science;">
<meta name="citation_reference" content="citation_title=The psychometric properties of the late positive potential during emotion processing and regulation;,citation_author=Tim P. Moran;,citation_author=Alexander A. Jendrusina;,citation_author=Jason S. Moser;,citation_publication_date=2013;,citation_cover_date=2013;,citation_year=2013;,citation_doi=10.1016/j.brainres.2013.04.018;,citation_volume=1516;,citation_journal_title=Brain Research;">
<meta name="citation_reference" content="citation_title=Affective picture processing: An integrative review of ERP findings;,citation_author=Jonas K. Olofsson;,citation_author=Steven Nordin;,citation_author=Henrique Sequeira;,citation_author=John Polich;,citation_publication_date=2008;,citation_cover_date=2008;,citation_year=2008;,citation_issue=3;,citation_doi=10.1016/j.biopsycho.2007.11.006;,citation_volume=77;,citation_journal_title=Biological Psychology;">
<meta name="citation_reference" content="citation_title=Selective visual attention to emotional pictures: Interactions of task-relevance and emotion are restricted to the late positive potential;,citation_author=Sebastian Schindler;,citation_author=Thomas Straube;,citation_publication_date=2020;,citation_cover_date=2020;,citation_year=2020;,citation_issue=9;,citation_doi=10.1111/psyp.13585;,citation_volume=57;,citation_journal_title=Psychophysiology;">
<meta name="citation_reference" content="citation_title=Affective picture processing: The late positive potential is modulated by motivational relevance;,citation_author=Harald T. Schupp;,citation_author=Bruce N. Cuthbert;,citation_author=Margaret M. Bradley;,citation_author=John T. Cacioppo;,citation_author=Tiffany Ito;,citation_author=Peter J. Lang;,citation_publication_date=2000;,citation_cover_date=2000;,citation_year=2000;,citation_issue=2;,citation_doi=10.1111/1469-8986.3720257;,citation_volume=37;,citation_journal_title=Psychophysiology;">
<meta name="citation_reference" content="citation_title=A context-based theory of recency and contiguity in free recall;,citation_author=Per B. Sederberg;,citation_author=Marc W. Howard;,citation_author=Michael J. Kahana;,citation_publication_date=2008;,citation_cover_date=2008;,citation_year=2008;,citation_issue=4;,citation_doi=10.1037/a0013396;,citation_volume=115;,citation_journal_title=Psychological Review;">
<meta name="citation_reference" content="citation_title=Enhanced emotional memory: Cognitive and neural mechanisms;,citation_author=Deborah Talmi;,citation_publication_date=2013;,citation_cover_date=2013;,citation_year=2013;,citation_issue=6;,citation_doi=10.1177/0963721413498893;,citation_volume=22;,citation_journal_title=Current Directions in Psychological Science;">
<meta name="citation_reference" content="citation_title=The emotion-elicited late positive potential is stable across five testing sessions;,citation_author=Anna Weinberg;,citation_author=Kelly A. Correa;,citation_author=Elizabeth S. Stevens;,citation_author=Stewart A. Shankman;,citation_publication_date=2021;,citation_cover_date=2021;,citation_year=2021;,citation_issue=11;,citation_doi=10.1111/psyp.13904;,citation_volume=58;,citation_journal_title=Psychophysiology;">
<meta name="citation_reference" content="citation_title=Contributions of arousal, attention, distinctiveness, and semantic relatedness to enhanced emotional memory: An event-related potential and electrocardiogram study;,citation_author=Vanessa C. Zarubin;,citation_author=Timothy K. Phillips;,citation_author=Eileen Robertson;,citation_author=Paige G. Bolton Swafford;,citation_author=Taylor Bunge;,citation_author=David Aguillard;,citation_author=Carolyn Martsberger;,citation_author=Katherine R. Mickley Steinmetz;,citation_publication_date=2020;,citation_cover_date=2020;,citation_year=2020;,citation_issue=3;,citation_doi=10.1007/s42761-020-00012-y;,citation_volume=1;,citation_journal_title=Affective Science;">
<meta name="citation_reference" content="citation_title=Bayesian model selection for group studies;,citation_author=Klaas Enno Stephan;,citation_author=Will D. Penny;,citation_author=Jean Daunizeau;,citation_author=Rosalyn J. Moran;,citation_author=Karl J. Friston;,citation_publication_date=2009;,citation_cover_date=2009;,citation_year=2009;,citation_issue=4;,citation_doi=10.1016/j.neuroimage.2009.03.025;,citation_volume=46;,citation_journal_title=NeuroImage;">
<meta name="citation_reference" content="citation_title=Bayesian model selection for group studies—revisited;,citation_author=Léonard Rigoux;,citation_author=Klaas Enno Stephan;,citation_author=Karl J. Friston;,citation_author=Jean Daunizeau;,citation_publication_date=2014;,citation_cover_date=2014;,citation_year=2014;,citation_doi=10.1016/j.neuroimage.2013.08.065;,citation_volume=84;,citation_journal_title=NeuroImage;">
</head>

<body class="quarto-light">

<header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Contribution of the Late Positive Potential to Emotional Memory: A Joint Neuro-Cognitive Approach to Memory Prediction</h1>
          </div>

    
    <div class="quarto-title-meta-container">
      <div class="quarto-title-meta-column-start">
            <div class="quarto-title-meta-author">
          <div class="quarto-title-meta-heading">Authors</div>
          <div class="quarto-title-meta-heading">Affiliations</div>
          
                <div class="quarto-title-meta-contents">
            <p class="author">Robin Hellerstedt </p>
          </div>
                <div class="quarto-title-meta-contents">
                    <p class="affiliation">
                        University
                      </p>
                  </div>
                      <div class="quarto-title-meta-contents">
            <p class="author">Jordan Gunn </p>
          </div>
                <div class="quarto-title-meta-contents">
                    <p class="affiliation">
                        University of Cambridge
                      </p>
                  </div>
                      <div class="quarto-title-meta-contents">
            <p class="author">Deborah Talmi </p>
          </div>
                <div class="quarto-title-meta-contents">
                    <p class="affiliation">
                        University of Cambridge
                      </p>
                  </div>
                    </div>
        
        <div class="quarto-title-meta">

                      
          
                
              </div>
      </div>
      <div class="quarto-title-meta-column-end quarto-other-formats-target">
      <div class="quarto-alternate-formats"><div class="quarto-title-meta-heading">Other Formats</div><div class="quarto-title-meta-contents"><p><a href="index.docx"><i class="bi bi-file-word"></i>MS Word (apaquarto)</a></p></div><div class="quarto-title-meta-contents"><p><a href="index.pdf"><i class="bi bi-file-pdf"></i>PDF (apaquarto)</a></p></div></div></div>
    </div>



    <div class="quarto-other-links-text-target">
    <div class="quarto-code-links"><div class="quarto-title-meta-heading">Code Links</div><div class="quarto-title-meta-contents"><span><a href="https://github.com/githubpsyche/lpp_ecmr/" target="_blank"><i class="bi bi-github"></i>GitHub Repo</a></span></div></div></div>  </div>
</header><div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#computational-modeling-of-the-early-lpp-contribution-to-emotional-recall" id="toc-computational-modeling-of-the-early-lpp-contribution-to-emotional-recall" class="nav-link active" data-scroll-target="#computational-modeling-of-the-early-lpp-contribution-to-emotional-recall">Computational modeling of the Early-LPP contribution to emotional recall</a>
  <ul class="collapse">
  <li><a href="#ecmr-model-specification" id="toc-ecmr-model-specification" class="nav-link" data-scroll-target="#ecmr-model-specification">eCMR Model Specification</a></li>
  <li><a href="#encoding-strength-hypotheses" id="toc-encoding-strength-hypotheses" class="nav-link" data-scroll-target="#encoding-strength-hypotheses">Encoding-strength hypotheses</a></li>
  <li><a href="#model-comparison-design" id="toc-model-comparison-design" class="nav-link" data-scroll-target="#model-comparison-design">Model-comparison design</a></li>
  <li><a href="#pooled-estimation-and-evaluation" id="toc-pooled-estimation-and-evaluation" class="nav-link" data-scroll-target="#pooled-estimation-and-evaluation">Pooled estimation and evaluation</a></li>
  </ul></li>
  <li><a href="#model-comparison-results" id="toc-model-comparison-results" class="nav-link" data-scroll-target="#model-comparison-results">Model-comparison results</a>
  <ul class="collapse">
  <li><a href="#overall-comparison" id="toc-overall-comparison" class="nav-link" data-scroll-target="#overall-comparison">Overall comparison</a></li>
  <li><a href="#contribution-of-preferential-emotional-learning" id="toc-contribution-of-preferential-emotional-learning" class="nav-link" data-scroll-target="#contribution-of-preferential-emotional-learning">Contribution of preferential emotional learning</a></li>
  <li><a href="#contribution-of-early-lpp" id="toc-contribution-of-early-lpp" class="nav-link" data-scroll-target="#contribution-of-early-lpp">Contribution of Early LPP</a></li>
  <li><a href="#general-versus-emotion-dependent-early-lpp" id="toc-general-versus-emotion-dependent-early-lpp" class="nav-link" data-scroll-target="#general-versus-emotion-dependent-early-lpp">General versus Emotion-dependent Early LPP</a></li>
  <li><a href="#summary-and-scope" id="toc-summary-and-scope" class="nav-link" data-scroll-target="#summary-and-scope">Summary and scope</a></li>
  </ul></li>
  
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content quarto-banner-title-block" id="quarto-document-content">



  


<section id="computational-modeling-of-the-early-lpp-contribution-to-emotional-recall" class="level2">
<h2 class="anchored" data-anchor-id="computational-modeling-of-the-early-lpp-contribution-to-emotional-recall">Computational modeling of the Early-LPP contribution to emotional recall</h2>
<p>The behavioral and EEG analyses identified two forms of variation in recall. At the category level, negative items were recalled more often than neutral items. At the item level, Early LPP was more strongly associated with subsequent recall for negative than neutral items. The empirical analyses distinguish these patterns statistically, but they do not determine how trial-level Early LPP should be mapped onto the encoding mechanism proposed to produce emotional memory enhancement. We therefore tested whether using item-level Early LPP to scale learning strength could replace a category-wide increase in learning strength, or whether the two forms of modulation explained complementary variation in which items were recalled.</p>
<p>We organized this comparison around three focused questions. We tested (1) whether preferential learning of negative items improved prediction of which items were recalled; (2) whether scaling learning with item-level Early LPP could replace that category-wide advantage or improve prediction after the advantage was included; and (3) whether Early-LPP scaling was better applied to both negative and neutral items or only to negative items. We therefore crossed the presence or absence of preferential emotional learning with three LPP specifications: no LPP-based learning modulation, one relationship shared across negative and neutral items, or one relationship limited to negative items. This crossing produced six models. All six models used the same memory architecture. We first describe that shared architecture and show where preferential emotional learning and Early LPP altered learning strength. We then describe model fitting, compare the six models, and use simulations to determine which observed patterns the fitted models reproduced.</p>
<section id="ecmr-model-specification" class="level3">
<h3 class="anchored" data-anchor-id="ecmr-model-specification">eCMR Model Specification</h3>
<p>We modeled recall with an adaptation of emotional Context Maintenance and Retrieval (eCMR) <span class="citation" data-cites="talmi2019retrieved">(<a href="#ref-talmi2019retrieved" role="doc-biblioref">Talmi, Lohnas, and Daw 2019</a>)</span>. Like other retrieved-context models <span class="citation" data-cites="howard2002distributed polyn2009context">(<a href="#ref-howard2002distributed" role="doc-biblioref">Howard and Kahana 2002</a>; <a href="#ref-polyn2009context" role="doc-biblioref">Polyn, Norman, and Kahana 2009</a>)</span>, eCMR represents context as a continuously updated internal state that carries information from recently processed events. Studying an item changes this state and forms associations in both directions: the item can later reinstate aspects of its study context, and the current context can later provide retrieval support for the item. During free recall, items receiving greater support are more likely to be selected. Recalling an item then reinstates aspects of its study context, changing the cue that guides the next recall. In the present comparison, stronger context-to-item learning could therefore increase an item’s probability of entering the recalled set. We first specify this common retrieval mechanism and then define the learning-strength terms that differed across models.</p>
<p>Published eCMR distinguishes temporal and source information within the context representation. Temporal context represents the evolving sequence of recently processed events, whereas source context represents non-temporal information about an event—in the present model, whether an item was negative or neutral. Recalling an item reinstates both components, so its category-related source state can increase support for other items associated with similar source information. Published eCMR also allows preferential learning to strengthen the associations formed by negative items <span class="citation" data-cites="talmi2019retrieved">(<a href="#ref-talmi2019retrieved" role="doc-biblioref">Talmi, Lohnas, and Daw 2019</a>)</span>. All six models retained this source-representation mechanism: every model represented negative and neutral source information. The comparison varied the learning-strength terms applied within that shared representation, so a model without preferential emotional learning still distinguished negative and neutral items in source context.</p>
<p>The fitted model was an adaptation rather than an unchanged implementation of published eCMR. It omitted item-specific semantic similarities among the pictures and the published source-switch mechanism, in which a transition between negative and neutral categories produces additional disruption of temporal context. We omitted that mechanism because recall order was unavailable to diagnose category-boundary effects and because the present comparison concerned learning strength rather than temporal disruption at source transitions.</p>
<p>The implementation also differed from published eCMR in how it combined old and new context and in how it converted retrieval support into recall choices. We identify those differences when the corresponding operations are introduced below. These choices were fixed across all six model definitions, so their structural differences concerned the learning-strength terms rather than different retrieval architectures.</p>
<p>Within each list <span class="math inline">\(j\)</span>, each studied item <span class="math inline">\(i\)</span> occupied a unique one-hot feature slot <span class="math inline">\(\mathbf f_i\)</span>: one entry was 1 and all remaining entries were zero. The complete context state therefore contained the temporal and source components introduced above,</p>
<p><span class="math display">\[
\mathbf c_i=
\begin{bmatrix}
\mathbf c_i^T\\
\mathbf c_i^S
\end{bmatrix}.
\]</span></p>
<p>The two components were updated and normalized separately, but together formed one context representation rather than independent memory systems. Both components included a start-of-list state, and all context states and associations were initialized anew for each list.</p>
<p>Items and context interacted through two associative mappings with opposite directions. With column-vector notation, the complete feature-to-context mapping <span class="math inline">\(M^{FC}\)</span> transformed an item into contextual input, whereas the complete context-to-feature mapping <span class="math inline">\(M^{CF}\)</span> transformed the current context into support for candidate items:</p>
<p><span class="math display">\[
M^{FC}=
\begin{bmatrix}
M_T^{FC}\\
M_S^{FC}
\end{bmatrix},
\qquad
M^{CF}=
\begin{bmatrix}
M_T^{CF} &amp; M_S^{CF}
\end{bmatrix}.
\]</span></p>
<p>Core symbols are collected in Supplementary <a href="#tbl-model-notation" class="quarto-xref">Table&nbsp;6</a>.</p>
<p>Before study, the two associative mappings were initialized differently. The temporal block of the initial feature-to-context mapping associated each item with its own temporal feature, and the source block associated each item with its negative or neutral source feature; both had weight <span class="math inline">\(1-\gamma\)</span>. In the initial temporal context-to-feature block, the context feature paired with an item supplied support <span class="math inline">\(\delta\)</span>, whereas every other item-associated context feature supplied background support <span class="math inline">\(\alpha\)</span>. The source context-to-feature block began at zero, so source context supported items only through associations learned during study.</p>
<p>When an item was presented, each context component first received unit-length input from the corresponding feature-to-context block:</p>
<p><span class="math display">\[
\mathbf u_i^T=\mathcal N\!\left(M_T^{FC}\mathbf f_i\right),
\qquad
\mathbf u_i^S=\mathcal N\!\left(M_S^{FC}\mathbf f_i\right),
\]</span></p>
<p>where <span class="math inline">\(\mathcal N(\mathbf v)=\mathbf v/\sqrt{\sum_k v_k^2+\epsilon}\)</span> and <span class="math inline">\(\epsilon\)</span> is machine epsilon. Each preceding context state then moved toward its input. Smaller encoding-drift values retained more of the preceding state; larger values gave the current item greater influence.</p>
<p>The fitted implementation performed this movement with the following componentwise integration operator:</p>
<p><span class="math display">\[
\begin{aligned}
\boldsymbol\rho(\mathbf c,\mathbf u,\beta)
&amp;=
\sqrt{
\mathbf 1+\beta^2
\left[
(\mathbf c\odot\mathbf u)^2-\mathbf 1
\right]
}
-
\beta(\mathbf c\odot\mathbf u),\\
\mathcal U(\mathbf c,\mathbf u,\beta)
&amp;=
\mathcal N\!\left[
\boldsymbol\rho(\mathbf c,\mathbf u,\beta)\odot\mathbf c
+
\beta\mathbf u
\right].
\end{aligned}
\]</span></p>
<p>Here, <span class="math inline">\(\odot\)</span>, the square, and the square root operate elementwise. The retention vector <span class="math inline">\(\boldsymbol\rho\)</span> controlled how much of each dimension of the preceding state remained after the new input was incorporated. Temporal and source context were then updated separately:</p>
<p><span class="math display">\[
\mathbf c_i^T
=
\mathcal U(\mathbf c_{i-1}^T,\mathbf u_i^T,\beta_{\mathrm{enc}}^T),
\qquad
\mathbf c_i^S
=
\mathcal U(\mathbf c_{i-1}^S,\mathbf u_i^S,\beta_{\mathrm{enc}}^S).
\]</span></p>
<p>This componentwise retention-and-renormalization rule differs from the scalar retention coefficient in the published CMR and eCMR equations.</p>
<p>Both context components were updated before the item’s associations were learned. The item was therefore bound to temporal and source states that it had already helped create, rather than to the states that preceded its presentation. This post-update order was held fixed across the comparison.</p>
<p>Feature-to-context learning stored the updated state that a later presentation or recall of the item could reinstate. The same fitted rate <span class="math inline">\(\gamma\)</span> applied to the temporal and source blocks:</p>
<p><span class="math display">\[
\Delta M_{T,i}^{FC}
=
\gamma\mathbf c_i^T\mathbf f_i^{\mathsf T},
\qquad
\Delta M_{S,i}^{FC}
=
\gamma\mathbf c_i^S\mathbf f_i^{\mathsf T}.
\]</span></p>
<p>Context-to-feature learning stored the reverse associations through which context could later support the item:</p>
<p><span class="math display">\[
\Delta M_{T,i}^{CF}
=
\phi_i\mathbf f_i(\mathbf c_i^T)^{\mathsf T},
\qquad
\Delta M_{S,i}^{CF}
=
S_{ij}^S\mathbf f_i(\mathbf c_i^S)^{\mathsf T}.
\]</span></p>
<p>The temporal learning strength <span class="math inline">\(\phi_i=1+\phi_s\exp[-\phi_d(i-1)]\)</span> gave early list positions a temporary advantage: <span class="math inline">\(\phi_s\)</span> controlled its size and <span class="math inline">\(\phi_d\)</span> controlled its decay. The source learning strength <span class="math inline">\(S_{ij}^S\)</span> contained the same primacy gradient together with the emotional-learning and Early-LPP terms defined below. Placing both focal predictors on source context-to-item learning gave them one directly comparable route to recall, while temporal context-to-item learning remained unchanged.</p>
<p>At recall onset, <span class="math inline">\(\beta_{\mathrm{start}}\)</span> shifted both context components toward their start-of-list states. The current temporal and source states then supplied additive support for each item that had not yet been recalled:</p>
<p><span class="math display">\[
a_i
=
\left[M^{CF}\mathbf c\right]_i
=
\left[M_T^{CF}\mathbf c^T\right]_i
+
\left[M_S^{CF}\mathbf c^S\right]_i.
\]</span></p>
<p>The choice-sensitivity parameter <span class="math inline">\(\tau_c\)</span> converted support into choice weights proportional to <span class="math inline">\(a_i^{\tau_c}\)</span>. The implementation evaluated these powers in log space and rescaled all weights by a common constant to avoid numerical overflow; this rescaling preserved their relative values. After machine epsilon was added to each available item’s weight, let <span class="math inline">\(q_i\)</span> denote the resulting positive value. The probability of the next recalled item was</p>
<p><span class="math display">\[
P(R_t=i\mid\mathcal A_t)
=
\frac{q_i}{\sum_{k\in\mathcal A_t}q_k},
\qquad i\in\mathcal A_t,
\]</span></p>
<p>where <span class="math inline">\(\mathcal A_t\)</span> is the set of studied items still available at recall step <span class="math inline">\(t\)</span>. Larger <span class="math inline">\(\tau_c\)</span> made the model more likely to select the item with greater support.</p>
<p>After an item was recalled, temporal context moved toward its retrieved temporal input at rate <span class="math inline">\(\beta_{\mathrm{rec}}^T\)</span>, and source context fully moved toward its retrieved source input by fixing <span class="math inline">\(\beta_{\mathrm{rec}}^S=1\)</span>. The retrieved source input contained both the item’s category feature and the source state learned during study.</p>
<p>Full source reinstatement was a fixed modeling constraint, not a conclusion from the data: without recall order, we treated partial source reinstatement as difficult to distinguish from source-learning strength and recall-choice sensitivity. The recalled item was then removed from the available set, so repeated recalls were disallowed. Context-guided selection and reinstatement complete the pathway through which source learning strength can change which items enter the recalled set.</p>
</section>
<section id="encoding-strength-hypotheses" class="level3">
<h3 class="anchored" data-anchor-id="encoding-strength-hypotheses">Encoding-strength hypotheses</h3>
<p>Every model estimated a shared source-learning baseline <span class="math inline">\(\omega\phi_i\)</span>. The parameter <span class="math inline">\(\omega\)</span> scaled source learning relative to temporal learning, for which the corresponding scale was fixed at 1. Estimating <span class="math inline">\(\omega\)</span> in every model allowed source context to contribute even when neither focal mechanism was enabled. The first focal term allowed negative items to receive a category-wide emotional-learning multiplier on this shared baseline.</p>
<p>Preferential emotional learning was represented by <span class="math inline">\(\phi_{\mathrm{emot}}^{e_i}\)</span>, where <span class="math inline">\(e_i=1\)</span> for a negative item and <span class="math inline">\(e_i=0\)</span> for a neutral item. The multiplier therefore equaled <span class="math inline">\(\phi_{\mathrm{emot}}\)</span> for negative items and 1 for neutral items. Models without the preferential emotional-learning term fixed <span class="math inline">\(\phi_{\mathrm{emot}}=1\)</span>, whereas models testing preferential emotional learning estimated the multiplier over the range <span class="math inline">\((0,10]\)</span>. Values above 1 strengthened source context-to-item learning for negative items relative to neutral items, whereas values below 1 attenuated it. That range allowed attenuation as well as enhancement of negative-item learning; “preferential emotional learning” names the directional hypothesis, and interpreting the fitted term as enhancement requires an estimate above 1. The category-wide emotional-learning multiplier can change the average recall difference between negative and neutral items, but it cannot distinguish two negative items on the basis of their different Early-LPP amplitudes. The Early-LPP terms supplied that item-level variation.</p>
<p>For item <span class="math inline">\(i\)</span> on 20-item study-test list <span class="math inline">\(j\)</span>, the model used within-list mean-centered Early LPP,</p>
<p><span class="math display">\[
z_{ij}
=
\mathrm{EarlyLPP}_{ij}
-
\overline{\mathrm{EarlyLPP}}_j.
\]</span></p>
<p>A positive value of <span class="math inline">\(z_{ij}\)</span> means that an item elicited a larger Early LPP than the average item on the same list; a negative value means that it elicited a smaller one. This predictor isolates within-list variation and removes differences between list means by construction. The present models can therefore test whether relatively larger Early LPP predicts which items enter a list’s recalled set, but not whether lists with larger average Early LPP produce more recalls. The preceding empirical regression did not separate within-list variation from differences among list means and participants. The computational coefficient addresses only the within-list relationship and is therefore not a numerical counterpart of the empirical regression coefficient.</p>
<p>Source learning strength was the product of the ordinary source-learning baseline, the category-wide emotional-learning multiplier, and an item-level Early-LPP multiplier:</p>
<p><span class="math display">\[
S_{ij}^S
=
\omega\phi_i
\times
\phi_{\mathrm{emot}}^{e_i}
\times
\exp\!\left[
\kappa z_{ij}
+
\kappa_{\mathrm{emot}}e_i z_{ij}
\right].
\]</span></p>
<p>The coefficient <span class="math inline">\(\kappa\)</span> is the General Early-LPP slope on log learning strength, and <span class="math inline">\(\kappa_{\mathrm{emot}}\)</span> is an additional negative-item slope. The resulting log-learning slope is <span class="math inline">\(\kappa\)</span> for neutral items and <span class="math inline">\(\kappa+\kappa_{\mathrm{emot}}\)</span> for negative items. At the list mean, where <span class="math inline">\(z_{ij}=0\)</span>, the Early-LPP multiplier equals 1 and the model recovers its ordinary category-level learning baseline. The exponential link guarantees positive learning strength, but positivity is not its only implication: the link assumes that a one-unit Early-LPP difference produces a proportional rather than a constant absolute change in learning. The model comparison tests whether one such proportional relationship improves prediction when it applies to both categories or only to negative items.</p>
<p>No-LPP models fixed both Early-LPP coefficients at zero. General-LPP models estimated <span class="math inline">\(\kappa\)</span> and fixed <span class="math inline">\(\kappa_{\mathrm{emot}}=0\)</span>, applying one slope to negative and neutral items. Emotion-dependent-LPP models fixed <span class="math inline">\(\kappa=0\)</span> and estimated <span class="math inline">\(\kappa_{\mathrm{emot}}\)</span>, applying one slope only to negative items. General and Emotion-dependent models therefore estimated the same number of parameters and differed only in the items to which their single Early-LPP slope applied. The empirical interaction motivated this matched comparison, but the model comparison determined which mapping better predicted the recalled sets.</p>
</section>
<section id="model-comparison-design" class="level3">
<h3 class="anchored" data-anchor-id="model-comparison-design">Model-comparison design</h3>
<p>Crossing a fixed or freely estimated emotional-learning multiplier with the three Early-LPP mappings produced the six models in <a href="#tbl-primary-ecmr-comparison" class="quarto-xref">Table&nbsp;1</a>.</p>
<div id="tbl-primary-ecmr-comparison" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-primary-ecmr-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Six models formed by crossing Early-LPP modulation with a fixed or estimated emotional-learning multiplier. All models contained temporal and negative/neutral source-context components; parenthetical values are numbers of free parameters. Estimating the multiplier tested the directional hypothesis of preferential emotional learning while also permitting attenuation.
</figcaption>
<div aria-describedby="tbl-primary-ecmr-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Early-LPP modulation</th>
<th style="text-align: left;">Emotional-learning multiplier fixed at 1</th>
<th style="text-align: left;">Emotional-learning multiplier estimated</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">None</td>
<td style="text-align: left;">Source-context baseline (11)</td>
<td style="text-align: left;">Preferential-learning model (12)</td>
</tr>
<tr class="even">
<td style="text-align: left;">General</td>
<td style="text-align: left;">General-LPP model (12)</td>
<td style="text-align: left;">Preferential learning + General-LPP model (13)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Emotion-dependent</td>
<td style="text-align: left;">Emotion-dependent-LPP model (12)</td>
<td style="text-align: left;">Preferential learning + Emotion-dependent-LPP model (13)</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Canonical implementation identifiers corresponding to these manuscript labels are reported in Supplementary <a href="#tbl-registry-mapping" class="quarto-xref">Table&nbsp;5</a>.</p>
<p>The grid supports the three comparisons introduced at the beginning of this section. Within each row, comparing the two columns tests whether freeing the emotional-learning multiplier improves prediction while holding the Early-LPP mapping fixed. Within each column, comparing an Early-LPP model with the No-LPP model tests whether the neural measure adds predictive information while holding fixed whether the emotional-learning multiplier was estimated. Finally, comparing General with Emotion-dependent LPP within either column tests two equal-complexity placements of one Early-LPP coefficient. The shared architecture in every cell makes these contrasts interpretable.</p>
<p>The grid also implements the substitution test proposed in the original motivation for constraining encoding strength with LPP. The General-LPP model with the emotional-learning multiplier fixed and the Preferential-learning model without LPP each had 12 free parameters. Both models added one scaling term to the same source context-to-item learning strength: the General-LPP model scaled learning from item-level LPP, whereas the Preferential-learning model scaled negative-item learning with <span class="math inline">\(\phi_{\mathrm{emot}}\)</span>. Their comparison therefore tests whether LPP-derived scaling can replace a free emotional-learning multiplier; the equal-complexity Emotion-dependent-LPP model provides a second LPP-derived alternative.</p>
<p><a href="#tbl-model-parameter-spec" class="quarto-xref">Table&nbsp;2</a> summarizes the parameters and the constraints that created the six cells. The eleven common free parameters governed temporal and source updating, pre-experimental support, associative learning, primacy, and recall choice. Estimating the emotional-learning multiplier or either one-slope Early-LPP mapping added one free parameter.</p>
<div id="tbl-model-parameter-spec" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-model-parameter-spec-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Parameters in the six-model specification. Bounds shown as open at zero were implemented with machine epsilon as the positive lower bound.
</figcaption>
<div aria-describedby="tbl-model-parameter-spec-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: left;">Role</th>
<th style="text-align: left;">Fitted range or fixed value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\beta_{\mathrm{enc}}^T\)</span></td>
<td style="text-align: left;">Temporal-context drift during study</td>
<td style="text-align: left;"><span class="math inline">\((0,1)\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\beta_{\mathrm{enc}}^S\)</span></td>
<td style="text-align: left;">Source-context drift during study</td>
<td style="text-align: left;"><span class="math inline">\((0,1)\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\beta_{\mathrm{start}}\)</span></td>
<td style="text-align: left;">Drift toward start-of-list context before recall</td>
<td style="text-align: left;"><span class="math inline">\((0,1)\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\beta_{\mathrm{rec}}^T\)</span></td>
<td style="text-align: left;">Temporal-context reinstatement after recall</td>
<td style="text-align: left;"><span class="math inline">\((0,1)\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\beta_{\mathrm{rec}}^S\)</span></td>
<td style="text-align: left;">Source-context reinstatement after recall</td>
<td style="text-align: left;"><span class="math inline">\(1\)</span> (fixed)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\alpha\)</span></td>
<td style="text-align: left;">Shared pre-experimental context-to-item support</td>
<td style="text-align: left;"><span class="math inline">\((0,100]\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\delta\)</span></td>
<td style="text-align: left;">Item-specific pre-experimental context-to-item support</td>
<td style="text-align: left;"><span class="math inline">\((0,100]\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\gamma\)</span></td>
<td style="text-align: left;">Feature-to-context learning rate</td>
<td style="text-align: left;"><span class="math inline">\((0,1)\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\phi_s\)</span></td>
<td style="text-align: left;">Primacy scale</td>
<td style="text-align: left;"><span class="math inline">\((0,100]\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\phi_d\)</span></td>
<td style="text-align: left;">Primacy decay</td>
<td style="text-align: left;"><span class="math inline">\((0,100]\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\tau_c\)</span></td>
<td style="text-align: left;">Recall-choice sensitivity</td>
<td style="text-align: left;"><span class="math inline">\((0,100]\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\omega\)</span></td>
<td style="text-align: left;">Source learning relative to temporal learning</td>
<td style="text-align: left;"><span class="math inline">\((0,10]\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\phi_{\mathrm{emot}}\)</span></td>
<td style="text-align: left;">Emotional-learning multiplier for negative items</td>
<td style="text-align: left;"><span class="math inline">\(1\)</span> (fixed) or <span class="math inline">\((0,10]\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\kappa\)</span></td>
<td style="text-align: left;">General Early-LPP slope on log learning strength</td>
<td style="text-align: left;"><span class="math inline">\(0\)</span> (fixed) or <span class="math inline">\([0,0.2145]\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\kappa_{\mathrm{emot}}\)</span></td>
<td style="text-align: left;">Emotion-dependent Early-LPP slope increment</td>
<td style="text-align: left;"><span class="math inline">\(0\)</span> (fixed) or <span class="math inline">\([0,0.2145]\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The primary grid does not estimate General and emotion-dependent Early-LPP coefficients simultaneously. It therefore asks whether one coefficient is more useful when shared by both categories or limited to negative items; it does not test whether a residual General component is exactly zero after an emotion-dependent component is fitted. The same learning-strength equation also defines a Full-LPP mapping in which <span class="math inline">\(\kappa\)</span> and <span class="math inline">\(\kappa_{\mathrm{emot}}\)</span> are estimated together. In that mapping, <span class="math inline">\(\kappa_{\mathrm{emot}}\)</span> is formally an additional negative-item slope; when <span class="math inline">\(\kappa=0\)</span>, it supplies the entire negative-item slope. We fitted the two source-context Full-LPP variants exploratorily, but their best-found solutions did not consistently recover the likelihoods of their nested one-slope models. We therefore excluded them from the primary comparison and report them separately as optimization-incomplete fits.</p>
<p>The comparison also holds source context constant across all six models. It can test learning-strength terms within that architecture, but it cannot establish that the predictive Early-LPP relationship is specific to source-context rather than temporal-context learning. Having defined the alternatives, we next describe the common evidence used to compare them.</p>
</section>
<section id="pooled-estimation-and-evaluation" class="level3">
<h3 class="anchored" data-anchor-id="pooled-estimation-and-evaluation">Pooled estimation and evaluation</h3>
<p>The modeling dataset matched each of the 6,840 study events to its recall outcome and Early-LPP value. As described in the preceding EEG methods, each single-trial ERP was first standardized relative to its own prestimulus interval, using the mean and standard deviation from <span class="math inline">\(-200\)</span> to 0 ms separately for each electrode. Early LPP was then extracted from the prespecified 400–1000 ms window and centroparietal electrodes.</p>
<p>Early-LPP values were unavailable for 371 events (5.4%). Before within-list centering, these values were imputed in three steps: first from available items of the same condition on the same participant’s list, then from all available items on that list if the condition-specific mean was unavailable, and finally from the dataset-wide mean for the corresponding condition. Recall status was not used in the imputation. This procedure yielded one complete 20-item input sequence for each list.</p>
<p>Each model was fitted with one parameter vector shared across all 342 study-test lists from 38 participants. The pooled analysis asks whether one parameterization captures the population-level pattern across the full dataset. It does not estimate participant-specific model parameters or individual differences. This restriction is important because each participant contributed only nine lists, too few independent list histories to support stable estimation of 11 to 13 parameters per participant.</p>
<p>The available recall records identified which items were recalled, but their output order was not available for modeling. This creates a problem because eCMR assigns probability to an ordered recall sequence: after each recall, the retrieved item changes context and therefore changes the probabilities of subsequent recalls. An unordered set of <span class="math inline">\(n_j\)</span> items is compatible with <span class="math inline">\(n_j!\)</span> possible orders. Enumerating all of those orders was impractical, so we approximated the evidence for each recalled set using 50 sampled orders.</p>
<p>Let <span class="math inline">\(\mathcal S_j\)</span> denote the items recalled from list <span class="math inline">\(j\)</span>, let <span class="math inline">\(n_j=|\mathcal S_j|\)</span>, let <span class="math inline">\(\pi_{jk}\)</span> be the <span class="math inline">\(k\)</span>th sampled ordering of those items, and let <span class="math inline">\(\boldsymbol\theta\)</span> denote a model’s parameter vector. For each list, the model was supplied with <span class="math inline">\(n_j\)</span> and evaluated on which studied items composed <span class="math inline">\(\mathcal S_j\)</span>. Using <span class="math inline">\(K=50\)</span> fixed sampled orders, the fitted score for the set was</p>
<p><span class="math display">\[
\widetilde P(\mathcal S_j\mid\boldsymbol\theta,n_j)
=
\frac{1}{K}
\sum_{k=1}^{K}
\prod_{t=1}^{n_j}
P\!\left(
R_{jt}=\pi_{jk,t}
\mid
\pi_{jk,1:(t-1)},
\boldsymbol\theta
\right).
\]</span></p>
<p>Each product in this expression is the probability of one possible ordered recall sequence; the outer average combines the 50 sampled sequences. Multiplying the average by <span class="math inline">\(n_j!\)</span> would estimate the full sum over compatible orders. Because this factor depends only on the observed list and not on the model parameters, omitting it adds the same constant to every negative log-likelihood (NLL). It therefore does not change fitted parameters; after model complexity is considered, it likewise does not change differences or rankings under Akaike’s information criterion (AIC), defined below. The same sampled orders and random seed were used for every model, so differences between models could not arise from evaluating different order samples.</p>
<p>Termination events were excluded from the likelihood. Accordingly, the model predicts which items enter the recalled set conditional on the number of items the participant recalled from that list. The analysis does not explain why that number of items was recalled and does not test a process for deciding when recall stops. Stopping may depend on the state of retrieval in free recall, but evaluating such a process requires a separate, validated termination model. The current likelihood keeps the present comparison focused on recalled-item identity.</p>
<p>We minimized the summed negative log of the approximate set scores using differential evolution, a population-based parameter search <span class="citation" data-cites="storn1997differential">(<a href="#ref-storn1997differential" role="doc-biblioref">Storn and Price 1997</a>)</span>. Each optimization began with a Latin-hypercube sample that spread its initial candidate vectors across the allowed parameter space. The search population contained 15 candidate vectors per free parameter, yielding 165, 180, or 195 candidates for models with 11, 12, or 13 free parameters, respectively. The crossover probability was 0.9, the differential weight varied between 0.5 and 1.0, and the relative convergence tolerance was <span class="math inline">\(10^{-4}\)</span>. Optimization continued for at most 1,000 generations and was repeated from three independent starts; the lowest NLL found across the three starts was retained.</p>
<p>The Early-LPP coefficients were constrained to be nonnegative in accordance with the directional empirical hypothesis. Their upper bound of 0.2145 limited either Early-LPP term to a tenfold multiplier at the largest observed centered Early LPP. The resulting estimates and rankings are conditional on this search budget and these parameter ranges.</p>
<p>Lower NLL indicates that a model assigned greater probability to the observed recalled sets. We compared the best-found solutions using Akaike’s information criterion, <span class="math inline">\(\mathrm{AIC}=2\mathrm{NLL}+2p\)</span>, where <span class="math inline">\(p\)</span> is the number of free parameters <span class="citation" data-cites="burnham2002model">(<a href="#ref-burnham2002model" role="doc-biblioref">Burnham and Anderson 2002</a>)</span>. Lower AIC indicates a better trade-off between conditional fit and model complexity. AIC establishes whether an optional learning term improved prediction enough to offset its additional parameter, but AIC does not show which empirical pattern that term reproduced. We therefore paired the model comparisons with simulations designed to make the fitted terms interpretable.</p>
<p>For each fitted parameter vector, we generated 200 complete simulated datasets containing the same 342 study lists and the same item-level Early-LPP values as the observed dataset. For each list, we generated exactly its observed number of recalled items, matching the conditioning used in the likelihood.</p>
<p>We summarized two patterns in each simulated dataset: the negative-versus-neutral recall difference and the remembered-versus-forgotten difference in within-list centered Early LPP. The parameters changed which studied items the model recalled; they did not change the observed Early-LPP value attached to an item. These summaries were not optimized as separate fitting targets. They are therefore explanatory diagnostics of the fitted recalled-set model, not independent or out-of-sample validation.</p>
</section>
</section>
<section id="model-comparison-results" class="level2">
<h2 class="anchored" data-anchor-id="model-comparison-results">Model-comparison results</h2>
<section id="overall-comparison" class="level3">
<h3 class="anchored" data-anchor-id="overall-comparison">Overall comparison</h3>
<p>The model combining preferential emotional learning with Emotion-dependent Early-LPP modulation had the lowest AIC (<a href="#tbl-model-fit" class="quarto-xref">Table&nbsp;3</a>). Its best-found NLL was 8240.310 with 13 free parameters, yielding an AIC of 16506.619. The overall ranking provides an initial orientation; the three planned comparisons determine what the ranking means. We report those comparisons in the order introduced above.</p>
<div id="tbl-model-fit" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-model-fit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Pooled fit of the six eCMR model variants. <span class="math inline">\(p\)</span> is the number of free parameters; NLL is the best-found negative log-likelihood across three differential-evolution starts; <span class="math inline">\(\Delta\)</span>AIC is relative to the lowest-AIC model.
</figcaption>
<div aria-describedby="tbl-model-fit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: right;"><span class="math inline">\(p\)</span></th>
<th style="text-align: right;">NLL</th>
<th style="text-align: right;">AIC</th>
<th style="text-align: right;"><span class="math inline">\(\Delta\)</span>AIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Source-context baseline</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">8313.531</td>
<td style="text-align: right;">16649.063</td>
<td style="text-align: right;">142.443</td>
</tr>
<tr class="even">
<td style="text-align: left;">General-LPP model</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">8300.740</td>
<td style="text-align: right;">16625.480</td>
<td style="text-align: right;">118.861</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Emotion-dependent-LPP model</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">8280.693</td>
<td style="text-align: right;">16585.387</td>
<td style="text-align: right;">78.768</td>
</tr>
<tr class="even">
<td style="text-align: left;">Preferential-learning model</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">8255.712</td>
<td style="text-align: right;">16535.424</td>
<td style="text-align: right;">28.805</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Preferential learning + General-LPP model</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">8251.121</td>
<td style="text-align: right;">16528.242</td>
<td style="text-align: right;">21.623</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Preferential learning + Emotion-dependent-LPP model</strong></td>
<td style="text-align: right;"><strong>13</strong></td>
<td style="text-align: right;"><strong>8240.310</strong></td>
<td style="text-align: right;"><strong>16506.619</strong></td>
<td style="text-align: right;"><strong>0.000</strong></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The fit statistics show whether a term improved conditional prediction, whereas the simulations show what empirical pattern the fitted term produced. <a href="#fig-model-diagnostics" class="quarto-xref">Figure&nbsp;1</a> displays the observed benchmarks and four predictions selected from the six models to isolate the three planned contrasts. For preferential emotional learning, the figure compares the Emotion-dependent-LPP model with and without a free emotional-learning multiplier. For the added contribution of Early LPP, it compares preferential emotional learning alone with a model that also included Emotion-dependent LPP. For the placement of the Early-LPP slope, it compares models that combined preferential emotional learning with either General or Emotion-dependent LPP. The left panels show the category-level recall pattern. The right panels show the item-level Early-LPP pattern separately for negative and neutral items. All six models remain in the numerical tables even though four representative predictions are sufficient to display the contrast logic.</p>
<div id="fig-model-diagnostics" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Five rows of paired horizontal grouped-bar charts show observed data followed by four selected model predictions. The left column compares negative and neutral recall rates. Emotion-dependent LPP without preferential emotional learning does not reproduce the observed negative-item advantage, whereas the three preferential-learning models do. The right column compares remembered and forgotten items' mean within-list centered Early LPP in each category. Preferential emotional learning without LPP shows little separation; General LPP separates the two categories to differing degrees; and Emotion-dependent LPP concentrates the separation among negative items.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-model-diagnostics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="work/lpp_model_results/diagnostic_figure.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figure&nbsp;1: Observed benchmarks and predictions from four of the six pooled source-context models. Left: overall recall rates by category. Right: mean within-list centered Early LPP by memory status and category. Observed error bars are 95% participant-cluster bootstrap intervals. Predicted error bars are central 95% intervals across 200 simulated datasets and show simulation variability, not parameter-estimation uncertainty. Simulations used each list’s observed recall count. The Early-LPP-by-memory-status pattern is a derived diagnostic, not a separately fitted target or out-of-sample validation."><img src="work/lpp_model_results/diagnostic_figure.png" class="img-fluid figure-img" style="width:85.0%" alt="Five rows of paired horizontal grouped-bar charts show observed data followed by four selected model predictions. The left column compares negative and neutral recall rates. Emotion-dependent LPP without preferential emotional learning does not reproduce the observed negative-item advantage, whereas the three preferential-learning models do. The right column compares remembered and forgotten items' mean within-list centered Early LPP in each category. Preferential emotional learning without LPP shows little separation; General LPP separates the two categories to differing degrees; and Emotion-dependent LPP concentrates the separation among negative items."></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-model-diagnostics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Observed benchmarks and predictions from four of the six pooled source-context models. Left: overall recall rates by category. Right: mean within-list centered Early LPP by memory status and category. Observed error bars are 95% participant-cluster bootstrap intervals. Predicted error bars are central 95% intervals across 200 simulated datasets and show simulation variability, not parameter-estimation uncertainty. Simulations used each list’s observed recall count. The Early-LPP-by-memory-status pattern is a derived diagnostic, not a separately fitted target or out-of-sample validation.
</figcaption>
</figure>
</div>
</section>
<section id="contribution-of-preferential-emotional-learning" class="level3">
<h3 class="anchored" data-anchor-id="contribution-of-preferential-emotional-learning">Contribution of preferential emotional learning</h3>
<p>The first comparison asks whether preferential learning of negative items improves prediction of which items are recalled. Freeing the emotional-learning multiplier lowered AIC under every Early-LPP specification: by 113.639 points with no LPP, by 97.238 points with General LPP, and by 78.768 points with Emotion-dependent LPP. The fitted multiplier exceeded 1 in all three models, so the estimated term enhanced rather than attenuated negative-item learning. The recall-rate panels explain this consistent advantage. Models with preferential emotional learning produced negative-minus-neutral recall differences between 0.118 and 0.134, close to the observed difference of 0.124; models without preferential emotional learning produced differences between 0.001 and 0.019. Because every model represented negative and neutral source features, this result concerns preferential emotional learning rather than the mere presence of category information. Preferential emotional learning supplied category-level recall structure, leaving the item-level contribution of Early LPP as the next question.</p>
</section>
<section id="contribution-of-early-lpp" class="level3">
<h3 class="anchored" data-anchor-id="contribution-of-early-lpp">Contribution of Early LPP</h3>
<p>The second comparison asks whether Early LPP adds predictive information beyond a model with no EEG input. Without preferential emotional learning, General LPP lowered AIC by 23.582 points and Emotion-dependent LPP lowered it by 63.676 points relative to the source-context baseline. With preferential emotional learning, the corresponding AIC improvements were 7.182 and 28.805 points. Early LPP therefore improved conditional prediction when the emotional-learning multiplier was fixed and when it was estimated.</p>
<p>The equal-complexity substitution comparisons asked a different question and produced a different result. The Preferential-learning model had an AIC 90.057 points lower than the General-LPP model and 49.963 points lower than the Emotion-dependent-LPP model; all three models had 12 free parameters. Within the fitted specification and parameter ranges, neither LPP-derived scaling rule matched the free emotional-learning multiplier, even though Early LPP improved prediction when added to models with or without that multiplier. This pattern favors complementarity over substitution.</p>
<p>The Early-LPP panels identify the additional pattern captured by Early-LPP modulation. In the observed data, remembered items had a 0.403 larger mean centered Early LPP than forgotten items within the negative category, whereas the corresponding neutral-item difference was 0.021. Models without Early-LPP modulation produced little remembered-versus-forgotten separation in either category. Because the Early-LPP values themselves remained fixed, remembered–forgotten differences arose only when a model preferentially recalled items with larger values. Early-LPP modulation therefore supplied item-level information that the category-wide emotional-learning multiplier did not contain. Because both Early-LPP mappings added information, the final comparison asks where their single slope should apply.</p>
</section>
<section id="general-versus-emotion-dependent-early-lpp" class="level3">
<h3 class="anchored" data-anchor-id="general-versus-emotion-dependent-early-lpp">General versus Emotion-dependent Early LPP</h3>
<p>The third comparison contrasts one slope shared across categories with one slope limited to negative items. The two alternatives had equal numbers of parameters, so their AIC difference reflected fit rather than a difference in the complexity penalty. Emotion-dependent LPP lowered AIC by 40.094 points relative to General LPP when preferential emotional learning was absent and by 21.623 points when preferential emotional learning was present. The simulations clarify why: General LPP separated remembered and forgotten items in both categories, whereas Emotion-dependent LPP concentrated the separation among negative items, as in the observed pattern. When the models were each given one Early-LPP coefficient, that coefficient was therefore more useful when applied to negative items.</p>
<p>This comparison is conditional on the declared parameter ranges. In the model combining preferential emotional learning with General LPP, <span class="math inline">\(\hat\kappa=0.208\)</span>, or 97% of its upper bound of 0.2145, and no wider-bound sensitivity analysis was conducted. We therefore cannot establish whether the Emotion-dependent mapping would remain preferred under a wider Early-LPP bound. The supported conclusion is narrower: within the declared range and equal-complexity comparison, the Emotion-dependent mapping predicted the recalled sets better.</p>
<p>A second near-bound estimate cautions against interpreting the General-LPP coefficients in isolation. In the General-LPP fit with the emotional-learning multiplier fixed, the source-learning scale approached its upper bound: <span class="math inline">\(\hat\omega=9.047\)</span> on the range <span class="math inline">\((0,10]\)</span>. This pattern suggests that the source-learning scale and the General Early-LPP coefficient may compensate for one another.</p>
<p>The focal fitted parameters in <a href="#tbl-focal-parameters" class="quarto-xref">Table&nbsp;4</a> show that the preferred model used both proposed mechanisms. The preferred model, which combined preferential emotional learning with Emotion-dependent LPP, estimated a source-learning scale of 0.930, an emotional-learning multiplier of 1.946, and an emotion-dependent log-learning slope of 0.128. The source-learning scale, context drift, and choice sensitivity were estimated jointly with these terms, so isolated parameter magnitudes should not be assigned direct psychological meanings or compared across models without considering the complete parameter vector.</p>
<div id="tbl-focal-parameters" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-focal-parameters-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Fitted source-learning scale and parameters governing preferential emotional learning and Early-LPP modulation. Fixed entries are the values that disable the corresponding optional mechanism.
</figcaption>
<div aria-describedby="tbl-focal-parameters-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: right;"><span class="math inline">\(\omega\)</span></th>
<th style="text-align: right;"><span class="math inline">\(\phi_{\mathrm{emot}}\)</span></th>
<th style="text-align: right;"><span class="math inline">\(\kappa\)</span></th>
<th style="text-align: right;"><span class="math inline">\(\kappa_{\mathrm{emot}}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Source-context baseline</td>
<td style="text-align: right;">0.226</td>
<td style="text-align: right;">1 (fixed)</td>
<td style="text-align: right;">0 (fixed)</td>
<td style="text-align: right;">0 (fixed)</td>
</tr>
<tr class="even">
<td style="text-align: left;">General-LPP model</td>
<td style="text-align: right;">9.047</td>
<td style="text-align: right;">1 (fixed)</td>
<td style="text-align: right;">0.060</td>
<td style="text-align: right;">0 (fixed)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Emotion-dependent-LPP model</td>
<td style="text-align: right;">1.385</td>
<td style="text-align: right;">1 (fixed)</td>
<td style="text-align: right;">0 (fixed)</td>
<td style="text-align: right;">0.184</td>
</tr>
<tr class="even">
<td style="text-align: left;">Preferential-learning model</td>
<td style="text-align: right;">1.452</td>
<td style="text-align: right;">1.504</td>
<td style="text-align: right;">0 (fixed)</td>
<td style="text-align: right;">0 (fixed)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Preferential learning + General-LPP model</td>
<td style="text-align: right;">1.037</td>
<td style="text-align: right;">7.525</td>
<td style="text-align: right;">0.208</td>
<td style="text-align: right;">0 (fixed)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Preferential learning + Emotion-dependent-LPP model</td>
<td style="text-align: right;">0.930</td>
<td style="text-align: right;">1.946</td>
<td style="text-align: right;">0 (fixed)</td>
<td style="text-align: right;">0.128</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The exploratory Full-LPP fits did not resolve whether a residual General component remained. Their original best-of-three solutions failed a basic optimization check: their NLLs were 3.265 and 1.294 points above their nested Emotion-dependent models without and with preferential emotional learning, respectively. Evaluating each nested parameter vector through the corresponding Full likelihood at <span class="math inline">\(\kappa=0\)</span> reproduced the parent NLL exactly. We therefore excluded the Full variants from the six-model ranking, report both the original and embedded-parent evaluations in Supplementary <a href="#tbl-full-lpp-summary" class="quarto-xref">Table&nbsp;9</a>, and do not use them to infer whether a residual General component remains.</p>
</section>
<section id="summary-and-scope" class="level3">
<h3 class="anchored" data-anchor-id="summary-and-scope">Summary and scope</h3>
<p>Taken together, the comparisons support complementary roles for preferential emotional learning and Early-LPP modulation. The emotional-learning multiplier reproduced the higher recall rate for negative than neutral items. The item-level Early-LPP multiplier distinguished which negative items were recalled. The preferred specification combined preferential emotional learning with Emotion-dependent LPP. It implements the proposed pathway from Early LPP through source context-to-item learning strength to the conditional probability of entering the recalled set, while also reproducing the emotional-memory advantage. The comparison thereby implements the original proposal to use an independent neural measure to constrain the same source-learning pathway governed at the category level by <span class="math inline">\(\phi_{\mathrm{emot}}\)</span>. The results show that LPP-derived scaling complemented, rather than replaced, the fitted emotional-learning multiplier.</p>
<p>The conclusion is deliberately narrower than a general account of emotional memory. It concerns within-list variation in Early LPP and recalled-item identity conditional on the observed recall count, using one parameter vector shared across participants.</p>
<p>The analysis does not explain total recall or stopping and does not estimate effects of between-list mean Early LPP. It also does not characterize participant-specific mechanisms, compare source with temporal implementations, or identify Early LPP uniquely with attention, arousal, or stimulus significance. Those questions require different data or additional models rather than stronger interpretation of the present comparison.</p>
<p>Finally, the numerical conclusions are conditional on the 50-order recalled-set approximation, the declared parameter bounds, and the differential-evolution search. The mechanistic conclusions concern the stated eCMR adaptation, including its componentwise context update and its omission of semantic similarity and source-switch disruption. Within those limits, a category-wide emotional-learning multiplier and an emotion-dependent item-level neural multiplier accounted for complementary structure in the observed recalled sets.</p>
</section>
</section>


<div id="quarto-appendix" class="default"><section id="supplementary-material" class="level1 appendix"><h2 class="anchored quarto-appendix-heading">Supplementary material</h2><div class="quarto-appendix-contents">

<section id="model-label-mapping" class="level2">
<h2 class="anchored" data-anchor-id="model-label-mapping">Model-label mapping</h2>
<div id="tbl-registry-mapping" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-registry-mapping-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Mapping between the manuscript-facing labels and the executable model registry.
</figcaption>
<div aria-describedby="tbl-registry-mapping-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Manuscript label</th>
<th style="text-align: left;">Canonical registry identifier</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Source-context baseline</td>
<td style="text-align: left;"><code>CategoryOnly_eCMR</code></td>
</tr>
<tr class="even">
<td style="text-align: left;">General-LPP model</td>
<td style="text-align: left;"><code>CategoryOnly_eCMR_LPP_General</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Emotion-dependent-LPP model</td>
<td style="text-align: left;"><code>CategoryOnly_eCMR_LPP_EmotionalOnly</code></td>
</tr>
<tr class="even">
<td style="text-align: left;">Preferential-learning model</td>
<td style="text-align: left;"><code>EEM_eCMR</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Preferential learning + General-LPP model</td>
<td style="text-align: left;"><code>EEM_eCMR_LPP_General</code></td>
</tr>
<tr class="even">
<td style="text-align: left;">Preferential learning + Emotion-dependent-LPP model</td>
<td style="text-align: left;"><code>EEM_eCMR_LPP_EmotionalOnly</code></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="core-notation" class="level2">
<h2 class="anchored" data-anchor-id="core-notation">Core notation</h2>
<p><a href="#tbl-model-notation" class="quarto-xref">Table&nbsp;6</a> collects the formal objects that recur across the specification. The fitted parameters and their roles are listed separately in <a href="#tbl-model-parameter-spec" class="quarto-xref">Table&nbsp;2</a>.</p>
<div id="tbl-model-notation" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-model-notation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: Core notation used in the model specification and recalled-set likelihood.
</figcaption>
<div aria-describedby="tbl-model-notation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Symbol</th>
<th style="text-align: left;">Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(i\)</span>, <span class="math inline">\(j\)</span>, <span class="math inline">\(t\)</span></td>
<td style="text-align: left;">Studied item, study-test list, and recall-output position, respectively</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\mathbf f_i\)</span></td>
<td style="text-align: left;">One-hot feature vector identifying studied item <span class="math inline">\(i\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\mathbf c\)</span>, <span class="math inline">\(\mathbf c^T\)</span>, <span class="math inline">\(\mathbf c^S\)</span></td>
<td style="text-align: left;">Complete context state and its temporal and source components</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\mathbf u_i^T\)</span>, <span class="math inline">\(\mathbf u_i^S\)</span></td>
<td style="text-align: left;">Temporal and source contextual input generated by item <span class="math inline">\(i\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(M^{FC}\)</span>, <span class="math inline">\(M^{CF}\)</span></td>
<td style="text-align: left;">Complete feature-to-context and context-to-feature associative mappings</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(M_T^{FC}\)</span>, <span class="math inline">\(M_S^{FC}\)</span>, <span class="math inline">\(M_T^{CF}\)</span>, <span class="math inline">\(M_S^{CF}\)</span></td>
<td style="text-align: left;">Temporal and source blocks of the two associative mappings</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\phi_i\)</span></td>
<td style="text-align: left;">Serial-position-dependent primacy multiplier for item <span class="math inline">\(i\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(S_{ij}^S\)</span></td>
<td style="text-align: left;">Completed source context-to-item learning strength for item <span class="math inline">\(i\)</span> on list <span class="math inline">\(j\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(e_i\)</span></td>
<td style="text-align: left;">Negative-item indicator: 1 for negative and 0 for neutral</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(z_{ij}\)</span></td>
<td style="text-align: left;">Within-list mean-centered Early LPP for item <span class="math inline">\(i\)</span> on list <span class="math inline">\(j\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(a_i\)</span>, <span class="math inline">\(q_i\)</span></td>
<td style="text-align: left;">Context-derived support for item <span class="math inline">\(i\)</span> and its positive choice weight</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\mathcal A_t\)</span></td>
<td style="text-align: left;">Studied items still available at recall position <span class="math inline">\(t\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\mathcal S_j\)</span>, <span class="math inline">\(n_j\)</span></td>
<td style="text-align: left;">Observed recalled set from list <span class="math inline">\(j\)</span> and its size</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\boldsymbol\theta\)</span></td>
<td style="text-align: left;">Complete fitted parameter vector for one model</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="complete-pooled-parameter-estimates" class="level2">
<h2 class="anchored" data-anchor-id="complete-pooled-parameter-estimates">Complete pooled parameter estimates</h2>
<p><a href="#tbl-primary-model-key" class="quarto-xref">Table&nbsp;7</a> defines the compact model codes used in <a href="#tbl-model-parameters" class="quarto-xref">Table&nbsp;8</a>.</p>
<div id="tbl-primary-model-key" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-primary-model-key-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7: Key for the six primary model columns in <a href="#tbl-model-parameters" class="quarto-xref">Table&nbsp;8</a>.
</figcaption>
<div aria-describedby="tbl-primary-model-key-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Code</th>
<th style="text-align: left;">Emotional-learning multiplier</th>
<th style="text-align: left;">Early-LPP mapping</th>
<th style="text-align: left;">Manuscript label</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">A</td>
<td style="text-align: left;">Fixed at 1</td>
<td style="text-align: left;">None</td>
<td style="text-align: left;">Source-context baseline</td>
</tr>
<tr class="even">
<td style="text-align: center;">B</td>
<td style="text-align: left;">Fixed at 1</td>
<td style="text-align: left;">General</td>
<td style="text-align: left;">General-LPP model</td>
</tr>
<tr class="odd">
<td style="text-align: center;">C</td>
<td style="text-align: left;">Fixed at 1</td>
<td style="text-align: left;">Emotion-dependent</td>
<td style="text-align: left;">Emotion-dependent-LPP model</td>
</tr>
<tr class="even">
<td style="text-align: center;">D</td>
<td style="text-align: left;">Estimated</td>
<td style="text-align: left;">None</td>
<td style="text-align: left;">Preferential-learning model</td>
</tr>
<tr class="odd">
<td style="text-align: center;">E</td>
<td style="text-align: left;">Estimated</td>
<td style="text-align: left;">General</td>
<td style="text-align: left;">Preferential learning + General-LPP model</td>
</tr>
<tr class="even">
<td style="text-align: center;">F</td>
<td style="text-align: left;">Estimated</td>
<td style="text-align: left;">Emotion-dependent</td>
<td style="text-align: left;">Preferential learning + Emotion-dependent-LPP model</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="tbl-model-parameters" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-model-parameters-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8: Best-found pooled parameter estimates for the six primary models. Values are rounded for presentation; square brackets identify fixed values. Parameter roles and fitted ranges are reported in <a href="#tbl-model-parameter-spec" class="quarto-xref">Table&nbsp;2</a>.
</figcaption>
<div aria-describedby="tbl-model-parameters-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: right;">A</th>
<th style="text-align: right;">B</th>
<th style="text-align: right;">C</th>
<th style="text-align: right;">D</th>
<th style="text-align: right;">E</th>
<th style="text-align: right;">F</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\beta_{\mathrm{enc}}^{T}\)</span></td>
<td style="text-align: right;">0.86396</td>
<td style="text-align: right;">0.73472</td>
<td style="text-align: right;">0.75960</td>
<td style="text-align: right;">0.83243</td>
<td style="text-align: right;">0.00084</td>
<td style="text-align: right;">0.80907</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\beta_{\mathrm{enc}}^{S}\)</span></td>
<td style="text-align: right;">0.18153</td>
<td style="text-align: right;">0.02849</td>
<td style="text-align: right;">0.11016</td>
<td style="text-align: right;">0.04012</td>
<td style="text-align: right;">0.72584</td>
<td style="text-align: right;">0.08675</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\beta_{\mathrm{start}}\)</span></td>
<td style="text-align: right;">0.97321</td>
<td style="text-align: right;">0.98771</td>
<td style="text-align: right;">0.99999</td>
<td style="text-align: right;">0.99999</td>
<td style="text-align: right;">0.03122</td>
<td style="text-align: right;">0.99999</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\beta_{\mathrm{rec}}^{T}\)</span></td>
<td style="text-align: right;">0.70721</td>
<td style="text-align: right;">0.67079</td>
<td style="text-align: right;">0.14344</td>
<td style="text-align: right;">0.18358</td>
<td style="text-align: right;">0.05141</td>
<td style="text-align: right;">0.15337</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\beta_{\mathrm{rec}}^{S}\)</span></td>
<td style="text-align: right;">[1]</td>
<td style="text-align: right;">[1]</td>
<td style="text-align: right;">[1]</td>
<td style="text-align: right;">[1]</td>
<td style="text-align: right;">[1]</td>
<td style="text-align: right;">[1]</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\alpha\)</span></td>
<td style="text-align: right;">0.24130</td>
<td style="text-align: right;">3.53733</td>
<td style="text-align: right;">1.69400</td>
<td style="text-align: right;">3.81835</td>
<td style="text-align: right;">74.64477</td>
<td style="text-align: right;">1.85902</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\delta\)</span></td>
<td style="text-align: right;">68.959</td>
<td style="text-align: right;">28.732</td>
<td style="text-align: right;">39.126</td>
<td style="text-align: right;">18.541</td>
<td style="text-align: right;">48.979</td>
<td style="text-align: right;">27.334</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\gamma\)</span></td>
<td style="text-align: right;">0.79003</td>
<td style="text-align: right;">0.46162</td>
<td style="text-align: right;">0.13427</td>
<td style="text-align: right;">0.25922</td>
<td style="text-align: right;">0.28439</td>
<td style="text-align: right;">0.21391</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\phi_s\)</span></td>
<td style="text-align: right;">28.721</td>
<td style="text-align: right;">0.48668</td>
<td style="text-align: right;">0.19390</td>
<td style="text-align: right;">0.02896</td>
<td style="text-align: right;">2.35576</td>
<td style="text-align: right;">0.22806</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\phi_d\)</span></td>
<td style="text-align: right;">2.20620</td>
<td style="text-align: right;">1.38064</td>
<td style="text-align: right;">4.43143</td>
<td style="text-align: right;">1.40662</td>
<td style="text-align: right;">2.11887</td>
<td style="text-align: right;">57.41072</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\tau_c\)</span></td>
<td style="text-align: right;">0.19046</td>
<td style="text-align: right;">2.17085</td>
<td style="text-align: right;">1.75392</td>
<td style="text-align: right;">3.32237</td>
<td style="text-align: right;">1.19079</td>
<td style="text-align: right;">1.57723</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\omega\)</span></td>
<td style="text-align: right;">0.22586</td>
<td style="text-align: right;">9.04693</td>
<td style="text-align: right;">1.38513</td>
<td style="text-align: right;">1.45162</td>
<td style="text-align: right;">1.03720</td>
<td style="text-align: right;">0.92996</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\phi_{\mathrm{emot}}\)</span></td>
<td style="text-align: right;">[1]</td>
<td style="text-align: right;">[1]</td>
<td style="text-align: right;">[1]</td>
<td style="text-align: right;">1.50441</td>
<td style="text-align: right;">7.52498</td>
<td style="text-align: right;">1.94591</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\kappa\)</span></td>
<td style="text-align: right;">[0]</td>
<td style="text-align: right;">0.05973</td>
<td style="text-align: right;">[0]</td>
<td style="text-align: right;">[0]</td>
<td style="text-align: right;">0.20799</td>
<td style="text-align: right;">[0]</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\kappa_{\mathrm{emot}}\)</span></td>
<td style="text-align: right;">[0]</td>
<td style="text-align: right;">[0]</td>
<td style="text-align: right;">0.18410</td>
<td style="text-align: right;">[0]</td>
<td style="text-align: right;">[0]</td>
<td style="text-align: right;">0.12805</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="exploratory-full-lpp-fits" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-full-lpp-fits">Exploratory Full-LPP fits</h2>
<p><a href="#tbl-full-lpp-summary" class="quarto-xref">Table&nbsp;9</a> reports the original optimizer outputs and the explicitly evaluated nested-parent candidates. Because a model cannot fit worse than a nested model at the optimum, the nesting violations indicate incomplete optimization rather than evidence that the General slope harmed fit. With the same population-size factor used in the primary analysis, the 13- and 14-parameter Full models used 195 and 210 candidate vectors, respectively. The embedded-parent candidate was the best evaluated Full-LPP solution in each case, and its AIC continues to count the additional Full-model parameter. Neither candidate is treated as a demonstrated maximum-likelihood solution.</p>
<div id="tbl-full-lpp-summary" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-full-lpp-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9: Exploratory Full-LPP evaluations. The original Full solutions are the best outputs from three differential-evolution starts. The embedded-parent candidates set <span class="math inline">\(\kappa=0\)</span> and use the parameter vector from the corresponding Emotion-dependent model.
</figcaption>
<div aria-describedby="tbl-full-lpp-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Preferential emotional learning</th>
<th style="text-align: right;">Full-model <span class="math inline">\(p\)</span></th>
<th style="text-align: right;">Original Full NLL</th>
<th style="text-align: right;">Original Full AIC</th>
<th style="text-align: right;">NLL above nested model</th>
<th style="text-align: right;">Embedded-parent NLL</th>
<th style="text-align: right;">Best-evaluated Full AIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Absent</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">8283.958</td>
<td style="text-align: right;">16593.916</td>
<td style="text-align: right;">3.265</td>
<td style="text-align: right;">8280.693</td>
<td style="text-align: right;">16587.387</td>
</tr>
<tr class="even">
<td style="text-align: left;">Present</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">8241.604</td>
<td style="text-align: right;">16511.207</td>
<td style="text-align: right;">1.294</td>
<td style="text-align: right;">8240.310</td>
<td style="text-align: right;">16508.619</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><a href="#tbl-full-lpp-parameters" class="quarto-xref">Table&nbsp;10</a> reports the original optimizer parameter estimates. These values are retained for transparency, not interpreted individually. Parameter roles and fitted ranges are defined in <a href="#tbl-model-parameter-spec" class="quarto-xref">Table&nbsp;2</a>.</p>
<div id="tbl-full-lpp-parameters" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-full-lpp-parameters-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;10: Original parameter estimates from the two optimization-incomplete exploratory Full-LPP fits.
</figcaption>
<div aria-describedby="tbl-full-lpp-parameters-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: right;">Emotional-learning multiplier fixed at 1</th>
<th style="text-align: right;">Emotional-learning multiplier estimated</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\beta_{\mathrm{enc}}^{T}\)</span></td>
<td style="text-align: right;">0.63919</td>
<td style="text-align: right;">0.75269</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\beta_{\mathrm{enc}}^{S}\)</span></td>
<td style="text-align: right;">0.048073</td>
<td style="text-align: right;">0.090636</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\beta_{\mathrm{start}}\)</span></td>
<td style="text-align: right;">0.99928</td>
<td style="text-align: right;">0.99992</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\beta_{\mathrm{rec}}^{T}\)</span></td>
<td style="text-align: right;">0.19682</td>
<td style="text-align: right;">0.14939</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\beta_{\mathrm{rec}}^{S}\)</span></td>
<td style="text-align: right;">1 (fixed)</td>
<td style="text-align: right;">1 (fixed)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\alpha\)</span></td>
<td style="text-align: right;">6.4214</td>
<td style="text-align: right;">7.5665</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\delta\)</span></td>
<td style="text-align: right;">29.362</td>
<td style="text-align: right;">61.357</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\gamma\)</span></td>
<td style="text-align: right;">0.48335</td>
<td style="text-align: right;">0.26261</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\phi_s\)</span></td>
<td style="text-align: right;">0.29664</td>
<td style="text-align: right;">0.73550</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\phi_d\)</span></td>
<td style="text-align: right;">1.0567</td>
<td style="text-align: right;">0.85239</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\tau_c\)</span></td>
<td style="text-align: right;">3.1391</td>
<td style="text-align: right;">1.7813</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\omega\)</span></td>
<td style="text-align: right;">6.9497</td>
<td style="text-align: right;">3.5453</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\phi_{\mathrm{emot}}\)</span></td>
<td style="text-align: right;">1 (fixed)</td>
<td style="text-align: right;">1.7823</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\kappa\)</span></td>
<td style="text-align: right;">0.001684</td>
<td style="text-align: right;">0.006867</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\kappa_{\mathrm{emot}}\)</span></td>
<td style="text-align: right;">0.10562</td>
<td style="text-align: right;">0.11559</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>

</section>
</div></section><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-burnham2002model" class="csl-entry" role="listitem">
Burnham, Kenneth P., and David R. Anderson. 2002. <em>Model Selection and Multimodel Inference: A Practical Information-Theoretic Approach</em>. 2nd ed. New York: Springer. <a href="https://doi.org/10.1007/b97636">https://doi.org/10.1007/b97636</a>.
</div>
<div id="ref-howard2002distributed" class="csl-entry" role="listitem">
Howard, Marc W., and Michael J. Kahana. 2002. <span>“A Distributed Representation of Temporal Context.”</span> <em>Journal of Mathematical Psychology</em> 46 (3): 269–99. <a href="https://doi.org/10.1006/jmps.2001.1388">https://doi.org/10.1006/jmps.2001.1388</a>.
</div>
<div id="ref-polyn2009context" class="csl-entry" role="listitem">
Polyn, Sean M., Kenneth A. Norman, and Michael J. Kahana. 2009. <span>“A Context Maintenance and Retrieval Model of Organizational Processes in Free Recall.”</span> <em>Psychological Review</em> 116 (1): 129–56. <a href="https://doi.org/10.1037/a0014420">https://doi.org/10.1037/a0014420</a>.
</div>
<div id="ref-storn1997differential" class="csl-entry" role="listitem">
Storn, Rainer, and Kenneth Price. 1997. <span>“Differential Evolution – a Simple and Efficient Heuristic for Global Optimization over Continuous Spaces.”</span> <em>Journal of Global Optimization</em> 11 (4): 341–59. <a href="https://doi.org/10.1023/A:1008202821328">https://doi.org/10.1023/A:1008202821328</a>.
</div>
<div id="ref-talmi2019retrieved" class="csl-entry" role="listitem">
Talmi, Deborah, Lynn J. Lohnas, and Nathaniel D. Daw. 2019. <span>“A Retrieved Context Model of the Emotional Modulation of Memory.”</span> <em>Psychological Review</em> 126 (4): 455–85. <a href="https://doi.org/10.1037/rev0000132">https://doi.org/10.1037/rev0000132</a>.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>